- manala.apt/vars/main.yml
```pgp.mit.edu``` is too often down...
The same key is available on the more reliable ```keyserver.ubuntu.com```key server
> Switch mysql apt key server

- manala.skeleton/vars/main.yml
Automatically update global npm packages lead to totally unwanted behavior, where npm is itself updated across nodejs version.
Indeed, npm versions are softly mapped to nodejs versions ( 2/4, 3/5, 3/6, 4/7, 5/8), and - for instance - going to npm 5  with node < 8 could break toys.
> Remove npm packages update handling

- manala.skeleton/CHANGELOG.md
- manala.skeleton/vars/main.yml
> [Skeleton] Fix httpie installation

- manala.skeleton/CHANGELOG.md
- manala.skeleton/vars/main.yml
python-pathlib2 is available on wheezy via manala, and on jessie via backports, python-pkg-resources is already available in a poor version on wheezy, and in a decent version on jessie via backports
> [Skeleton] Respect thefuck dependencies

- manala.apt/CHANGELOG.md
- manala.apt/vars/main.yml
- manala.pam-ssh-agent-auth/CHANGELOG.md
- manala.pam-ssh-agent-auth/README.md
- manala.pam-ssh-agent-auth/tasks/install.yml
- manala.pam-ssh-agent-auth/tests/0100_install.goss.yml
- manala.pam-ssh-agent-auth/tests/0100_install.yml
- manala.pam-ssh-agent-auth/tests/0200_sudo.yml
Long story short: package is now available upstream (see: https://packages.debian.org/sid/libpam-ssh-agent-auth), and following the debian rules, changed its name from `libpam-ssh-agent-auth` to `pam-ssh-agent-auth`.
Btw, to keep a decent version, we still use by default our backported version
> [Pam Ssh Agent Auth] Change package

- manala.elasticsearch/tests/0204_install.5.yml
- manala.elasticsearch/tests/0304_config.5.yml
- manala.java/tests/0102_install.8.yml
- manala.nodejs/tests/0103_install.5.yml
- manala.nodejs/tests/0105_install.7.yml
- manala.nodejs/tests/0106_install.8.yml
- manala.nodejs/tests/0107_install.9.yml
I've just realized that we left behind some tests during debian stretch support.
Why ?
Because, we need to specify each distribution individually when we don't supports all of them.
Let's see an example, where - before stretch support - we wanted to exclude wheezy:
```
hosts:
- debian.jessie
```
It's easy to forgot to add an `debian.stretch` key, because the intention is not clear. Jessie only ? All but wheezy ?
Now, same example using ansible host exclusion (http://docs.ansible.com/ansible/latest/intro_patterns.html):
```
hosts:
- debian:!debian.wheezy
```
Aaaaah ! Nice, the intention is clear, and nothing to specify for adding stretch support :)
So, to focus on a specific distribution:
```
hosts: debian.jessie
```
So, to focus on a specific distributions, without forward compatibility: …
> Use hosts exclusion on tests

- manala.deploy/CHANGELOG.md
- manala.deploy/tasks/copied.yml
- manala.deploy/tasks/shared.yml
- manala.deploy/tests/0200_strategy.synchronize.goss.yml
- manala.deploy/tests/0400_shared.goss.yml
- manala.deploy/tests/0400_shared.yml
- manala.deploy/tests/0600_writable.goss.yml
- manala.deploy/tests/0600_writable.yml
- manala.deploy/tests/0800_removed.goss.yml
- manala.deploy/tests/0800_removed.yml
Right now, with recents ansible versions, trying to share an existing symbolic link breaks deploy:
```
failed: [xxx] (item=file_shared_existing_link) => {"failed": true, "item": "file_shared_existing_link", "msg": "Cannot touch other than files, directories, and hardlinks (/xxx//file_shared_existing_link is link)"}
```
> [Deploy] Only tries to touch non existing shared files

- manala.php/CHANGELOG.md
- manala.php/README.md
- manala.php/templates/fpm_pools/5.6/_base.j2
- manala.php/templates/fpm_pools/5/_base.j2
- manala.php/templates/fpm_pools/7.0/_base.j2
- manala.php/templates/fpm_pools/7.1/_base.j2
- manala.php/templates/fpm_pools/7.2/_base.j2
- manala.php/templates/fpm_pools/_macros.j2
- manala.php/tests/0600_fpm_pools.5.4.goss.yml
- manala.php/tests/0600_fpm_pools.5.4.yml
- manala.php/tests/0601_fpm_pools.5.5.goss.yml
- manala.php/tests/0601_fpm_pools.5.5.yml
- manala.php/tests/0602_fpm_pools.5.6_dotdeb.goss.yml
- manala.php/tests/0602_fpm_pools.5.6_dotdeb.yml
- manala.php/tests/0603_fpm_pools.5.6.goss.yml
- manala.php/tests/0603_fpm_pools.5.6.yml
- manala.php/tests/0604_fpm_pools.7.0_dotdeb.goss.yml
- manala.php/tests/0604_fpm_pools.7.0_dotdeb.yml
- manala.php/tests/0605_fpm_pools.7.0.goss.yml
- manala.php/tests/0605_fpm_pools.7.0.yml
- manala.php/tests/0606_fpm_pools.7.1.goss.yml
- manala.php/tests/0606_fpm_pools.7.1.yml
- manala.php/tests/0607_fpm_pools.7.2.goss.yml
- manala.php/tests/0607_fpm_pools.7.2.yml
Allow to pass environment variables to php pools : 
Env variables defined in `config` overwrite variables defined in `pool`.
```yml
manala_php_fpm_pools:
- file:  www.conf
template: fpm_pools/default.j2
env:
FOO: bar
BAR: 1
config:
- www:
- env[BAR]: 2
```
```php
array(4) {
["BAR"]=>
string(1) "2"
["FOO"]=>
string(3) "bar"
}
```
Env variables are casted to string :
```yaml
manala_php_fpm_pools:
- file: www.conf
template: fpm_pools/default.j2
www:
bool: yes
int: 1
float: 1.0
string: hello
```
```php
array(7) {
["string"]=>
string(5) "hello"
["bool"]=>
string(1) "1"
["float"]=>
string(3) "1.0"
["int"]=>
string(1) "1"
}
```
Variables order is not preserved.
> [Php] Allow to pass 'env' variables to php pools

- manala.environment/CHANGELOG.md
- manala.environment/README.md
- manala.environment/lookup_plugins/manala_environment_variables.py
- manala.environment/tests/0100_variables.goss.yml
- manala.environment/tests/0100_variables.yml
- manala.environment/tests/0101_variables_legacy.goss.yml
- manala.environment/tests/0101_variables_legacy.yml
> [Environment] Support non-scalar variable intepretation only in legacy mode

- manala.ohmyzsh/templates/users/php.dev.j2
Because I'm tired of sending `yarn Jenkinsfile` to my terminal by mistake by hitting tab after `yarn` 😄
> Add yarn ohmyzsh plugin by default

- manala.nginx/CHANGELOG.md
- manala.nginx/templates/configs/app_ssl_offloading.dev.j2
Disable client_max_body_size on ssl offloading to prevent `413 Payload Too Large` errors.
> Disable client_max_body_size on ssl offloading

- manala.php/CHANGELOG.md
- manala.php/defaults/main.yml
- manala.php/handlers/main.yml
- manala.php/tasks/install.yml
- manala.php/tasks/main.yml
- manala.php/tasks/services.yml
- manala.php/tests/0400_configs_global.5.4.yml
- manala.php/tests/0501_configs.5.5.yml
- manala.php/tests/0502_configs.5.6_dotdeb.yml
- manala.php/tests/0503_configs.5.6.yml
- manala.php/tests/0504_configs.7.0_dotdeb.yml
- manala.php/tests/0505_configs.7.0.yml
- manala.php/tests/0506_configs.7.1.yml
- manala.php/tests/0507_configs.7.2.yml
- manala.php/tests/0600_fpm_pools.5.4.yml
- manala.php/tests/0601_fpm_pools.5.5.yml
- manala.php/tests/0602_fpm_pools.5.6_dotdeb.yml
- manala.php/tests/0603_fpm_pools.5.6.yml
- manala.php/tests/0604_fpm_pools.7.0_dotdeb.yml
- manala.php/tests/0605_fpm_pools.7.0.yml
- manala.php/tests/0606_fpm_pools.7.1.yml
- manala.php/tests/0607_fpm_pools.7.2.yml
- manala.php/tests/0700_blackfire.5.4.yml
- manala.php/tests/0701_blackfire.5.5.yml
- manala.php/tests/0702_blackfire.5.6_dotdeb.yml
- manala.php/tests/0703_blackfire.5.6.yml
- manala.php/tests/0704_blackfire.7.0_dotdeb.yml
- manala.php/tests/0705_blackfire.7.0.yml
- manala.php/tests/0706_blackfire.7.1.yml
- manala.php/tests/0707_blackfire.7.2.yml
Just like debian do with its generic "php" package (see: https://packages.debian.org/stretch/php7.0)
> [Php] Provide "cli" and "fpm" as default sapis

- manala.proxmox/CHANGELOG.md
- manala.proxmox/tasks/instances.yml
This helps in situations where an instance must be started right after being created, but because creation takes few seconds, we have to loop until it has been created.
```
manala_proxmox_instances:
- hostname: foo
disk: 20
ostemplate: local:vztmpl/template.tar.gz
- hostname: foo
state: started
```
> [Proxmox] Loop over instances management until its ready

- manala.apparmor/README.md
- manala.git/README.md
- manala.gitlab/README.md
- manala.grafana/README.md
- manala.haproxy/README.md
- manala.maxscale/README.md
- manala.motd/README.md
- manala.mysql/README.md
- manala.postgresql/README.md
- manala.telegraf/README.md
- manala.vault/README.md
No need to use `playbook_dir` as its part of templates search path (see: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/playbook_pathing.rst)
Fix #120
Ping @yvalentin
> [All] Useless "playbook_dir" usage in documentation

- manala.apt/CHANGELOG.md
- manala.apt/vars/main.yml
Blacklist old stables instead of whitelist current stable.
Before:
```
ansible_distribution_release == 'stretch'
```
After:
```
ansible_distribution_release not in ['wheezy', 'jessie']
```
> [Apt] Cleanup distribution handling

- manala.php/CHANGELOG.md
- manala.php/lookup_plugins/manala_php_fpm_pools_config.py
See: https://github.com/php/php-src/blob/PHP-7.2.9/sapi/fpm/fpm/fpm_conf.c#L1447
> [Php] Empty environment variables raise errors as well as null ones

- manala.apt/CHANGELOG.md
- manala.apt/vars/main.yml
This one was hard to catch...
Long story short, `gnupg2` package on debian stretch has been updated to `2.1.18-8~deb9u3`, introducing strict gpg ring checks. Some of the apt keys starts to gently warns...
This was not a big deal, those keys remains valids, except that gpg now log warnings on stdout, and `apt-key` script don't set `--batch` flags when running gpg, which would allowed to silence those warnings.
Still not a real issue, btw...
The fact is when running `apt-key` in a non interactive shell (like in a vagrant/ansible situation), `/dev/tty` is not available, and the import fails miserably...
This is easily reproducible, running such an ansible playbook:
```
- hosts: all
vars:
manala_apt_preferences:
- nodejs@nodesource_4
- mysql@mysql_5_6
- mariadb@mariadb_10_2
- …
```
> [Apt] Switch back problematics keys sources from ubuntu keyserver to direct url

- manala.oauth2-proxy/CHANGELOG.md
- manala.oauth2-proxy/templates/config/default.j2
Fix oauth2-proxy with github provider : 
```yaml
manala_oauth2_proxy_config:
- http_address: "{{ ansible_eth0.ipv4.address }}:4280"
- upstreams:
- http://127.0.0.1:4440/
- request_logging: true
- provider: github
- github_org: github_org
- github_team: github_team
- email_domains:
- '*'
- client_id: ****
- client_secret: ****
- pass_access_token: true
- cookie_name: _oauth2_service
- cookie_secret: ****
- cookie_secure: true
- cookie_httponly: true
- cookie_expire: 168h
- cookie_refresh: 1h
```
> [oauth2_proxy] Fix missing config extra vars

- manala.apt/CHANGELOG.md
- manala.apt/lookup_plugins/manala_apt_repositories.py
- manala.apt/tests/0500_repositories.goss.1.yml
- manala.apt/vars/main.yml
This would help in some situations, like dotdeb repository, where automatic file name generator only take repository url into account, blocking multiple "flavors" by repository ("wheezy" and "wheezy-php56", for instance)
> [Apt] Repository file can be specified

- manala.skeleton/CHANGELOG.md
- manala.skeleton/vars/main.yml
Privilege in the projects the use of a php-cs-fix installed locally via Composer (`composer require friendsofphp/php-cs-fixer`)
> [Skeleton] Remove php-cs-fixer / phpcs / security-checker from PHP apps

- manala.skeleton/CHANGELOG.md
- manala.skeleton/vars/main.yml
According to the doc itself (https://dev.mysql.com/doc/refman/5.6/en/connecting.html):
> If the host is not specified or is localhost, a connection to the local host is assumed:
> On Unix, the client connects using a Unix socket file. The --socket option or the MYSQL_UNIX_PORT environment variable may be used to specify the socket name.
That's why we need to set *BOTH* app passwordless users, one for localhost, and one for anywhere (`%`)
> [Skeleton] Both allow app passwordless mysql connections from localhost and anywhere

- manala.logrotate/CHANGELOG.md
- manala.logrotate/README.md
- manala.logrotate/tasks/configs.yml
- manala.logrotate/tests/0200_configs.goss.1.yml
- manala.logrotate/tests/0200_configs.yml
Welcome to the hype:
```
manala_logrotate_configs:
...
- file: nginx_example_2
content: |
/var/log/nginx/example/*/*.log
/var/log/nginx/example/*/*/*.log {
size 200M
missingok
rotate 0
compress
delaycompress
notifempty
create 0640 www-data adm
sharedscripts
}
```
> [Logrotate] Handle configs content

- manala.telegraf/CHANGELOG.md
- manala.telegraf/handlers/main.yml
Avoid to break when some services (nginx, php-fpm, ...) are not yet started or reloaded during provisioning.
> [Telegraf] Remove check mode before restart

- roles/apt/CHANGELOG.md
- roles/apt/vars/main.yml
Upstream `GlusterFS` debian repository include architecture (amd64|arm64) in its url.
```
https://download.gluster.org/pub/gluster/glusterfs/6/LATEST/Debian/stretch/amd64/apt stretch main
https://download.gluster.org/pub/gluster/glusterfs/6/LATEST/Debian/stretch/arm64/apt stretch main
```
For this reason, we have to consider `amd64` and `arm64` as two dstinct repositories.
To keep backward compatibility, main repository remains the `amd64` one.
> [Apt] Drop GlusterFS arm64 support

- roles/nginx/templates/configs/app_php_fpm.dev.j2
- roles/nginx/templates/configs/app_php_fpm.prod.j2
- roles/nginx/templates/configs/app_php_fpm.test.j2
Every nginx packages (from debian or nginx) on every distributions (jessie/stretch/buster) already include `fastcgi_param HTTPS $https if_not_empty;` in `/etc/nginx/fastcgi_params` file.
No need to re-define it with the same value in our own templates :)
> [Php] Remove redundant HTTPS fastcgi parameter

- CHANGELOG.md
- roles/mysql/CHANGELOG.md
- roles/mysql/README.md
- roles/mysql/tasks/users.yml
In case of a simple `state: absent` user, privileges should not be required.
> [MySQL] Omit users privileges if not present

- CHANGELOG.md
- roles/cron/CHANGELOG.md
- roles/cron/README.md
- roles/cron/defaults/main.yml
- roles/cron/handlers/main.yml
- roles/cron/tasks/files.yml
- roles/cron/tests/0100_install.yml
- roles/cron/tests/0200_files.goss.yml
- roles/cron/tests/0200_files.yml
- roles/cron/tests/0300_services.yml
```
manala_cron_files_defaults:
user: qux # This will be applied by default to cron files
manala_cron_files:
- file: qux
jobs:
- name: foo-foo
job: whoami
- file: quux
user: quux # Override defaults
jobs:
- name: foo-foo
job: whoami
```
> [Cron] Handle defaults parameters for files

- CHANGELOG.md
- roles/ssh/CHANGELOG.md
- roles/ssh/templates/config/server/default.dev.j2
- roles/ssh/templates/config/server/default.test.j2
Bye bye messages on ssh connections:
```
Last login: Thu Jul  9 14:52:06 2020 from 10.0.2.2
```
> [Ssh] Stop printing last log on dev/test server config template

- CHANGELOG.md
- roles/docker/CHANGELOG.md
- roles/docker/README.md
- roles/docker/lookup_plugins/manala_docker_applications.py
- roles/docker/templates/applications/default.j2
- roles/docker/tests/0400_applications.goss.yml
- roles/docker/tests/0400_applications.yml
- roles/docker/tests/fixtures/applications/audiowaveform.j2
`image` was previously a mandatory application parameter on the `lookup` level.
It's now on the template level, allowing to use templates where image is already hard defined.
> [Docker] Allow applications templates

- CHANGELOG.md
- roles/apt/CHANGELOG.md
- roles/apt/README.md
- roles/apt/lookup_plugins/manala_apt_holds.py
- roles/apt/tasks/holds.yml
- roles/apt/tests/0700_holds.goss.yml
- roles/apt/tests/0700_holds.yml
before:
```
manala_apt_holds:
- package: bar
hold: true
- package: baz
hold: false
```
after:
```
manala_apt_holds:
- package: bar
state: present
- package: baz
state: absent
```
`hold` flag is deprecated, but remains active to ensure backward compatibility
> [Apt] Handle holds with state (present|absent|ignore)

- CHANGELOG.md
- roles/mongodb/CHANGELOG.md
- roles/mongodb/tasks/services.yml
'cause mongodb package now comes with a disabled (on startup) systemd service.
> [Mongodb] Explicitly enable service

- .github/workflows/collection-release.yml
- .travis.yml
- CHANGELOG.md
- galaxy.yml
- On lance le script prepare_collection.py
- On build et publish sur ansible-galaxy
- On parse la version dans galaxy.yml avec une action dédiée au yaml dans un step `get_version`
- On passe la version au step changelog qui couine si il ne l’a trouve pas
- On utilise la version du step changelog  pour créer et upload la release sur github, et non pas celui de get_version, comme ça on est sûr de jamais oublier le changelog
> Release(s) with Github actions

- roles/files/action_plugins/manala_files_attributes.py
If `task_vars` is not given as a parameter to some sub modules in attributes action plugin, important ansible variables such as `ansible_facts` could not be read.
This leads to issues like this:
```
TASK [manala.roles.files : attributes] *****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'ansible_facts'
fatal: [development]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
This fix simply ensure that `task_vars` are given in indentified situations.
> [Files] Fix task_vars issues

- CHANGELOG.md
- roles/backup_manager/CHANGELOG.md
- roles/backup_manager/README.md
- roles/backup_manager/templates/configs/_macros.j2
- roles/backup_manager/tests/0200_configs.goss.1.yml
- roles/backup_manager/tests/0200_configs.yml
Example:
```
manala_backup_manager_configs:
- file: foo.conf
config:
- BM_TARBALL_DIRECTORIES:
- foo
- bar
-
- baz
```
Result
```
export BM_TARBALL_DIRECTORIES="foo bar baz"
```
> [Backup Manager] Handle list configs parameters

- roles/haproxy/handlers/main.yml
- roles/haproxy/tasks/environment.yml
When the /etc/defaults/haproxy file is modified, haproxy needs a restart 
to pick up these changes. This implements just that.
> [Haproxy] Force restart on change

- CHANGELOG.md
- roles/mount/CHANGELOG.md
- roles/mount/tasks/points.yml
- roles/mysql/CHANGELOG.md
- roles/mysql/tasks/databases.yml
- roles/mysql/tasks/users.yml
- roles/systemd/CHANGELOG.md
- roles/systemd/tasks/services.yml
`equalto` was introduced in jinja 2.8, `eq` in jinja 2.10, and default debian jinja package version in stretch is 2.8
> [All] Switch from `eq` to more widely available `equalto` test

- CHANGELOG.md
- roles/mysql/CHANGELOG.md
- roles/mysql/README.md
- roles/mysql/tasks/users.yml
With `sql_log_bin: false` you can run `manala_mysql.users` on all cluster hosts without breaking log replication.
> [MySQL] Supports `sql_log_bin` directive on `manala_mysql_users`

- roles/apt/CHANGELOG.md
- roles/apt/vars/main.yml
- roles/mysql/tests/pre_tasks/galera_3.yml
Galera-3 deprecates Jessie from 3.32 (http://releases.galeracluster.com/galera-3/debian/dists/) 
This PR sets the apt source to the last version available on Jessie -> 3.31
(http://releases.galeracluster.com/galera-3.31/)
> [Apt] Set last jessie repo for galera-3

- CHANGELOG.md
- roles/sensu_go/CHANGELOG.md
- roles/sensu_go/defaults/main.yml
- roles/sensu_go/tasks/agent_config.yml
- roles/sensu_go/tasks/backend_config.yml
- roles/sensu_go/tests/0200_agent_config.goss.yml
- roles/sensu_go/tests/0201_backend_config.goss.yml
Improve security by restricting sensu configs to `sensu` user/group only.
> [sensu_go] Change default file permissions

- CHANGELOG.md
- roles/apt/CHANGELOG.md
- roles/apt/vars/main.yml
- roles/maxscale/CHANGELOG.md
- roles/maxscale/tests/0005_default.2.5.goss.yml
- roles/maxscale/tests/0005_default.2.5.yml
- roles/maxscale/tests/0006_default.6.1.goss.yml
- roles/maxscale/tests/0006_default.6.1.yml
- roles/maxscale/tests/0205_config.2.5.goss.yml
- roles/maxscale/tests/0205_config.2.5.yml
- roles/maxscale/tests/0206_config.6.1.goss.yml
- roles/maxscale/tests/0206_config.6.1.yml
- roles/maxscale/tests/0305_configs.2.5.goss.yml
- roles/maxscale/tests/0305_configs.2.5.yml
- roles/maxscale/tests/0306_configs.6.1.goss.yml
- roles/maxscale/tests/0306_configs.6.1.yml
- roles/maxscale/tests/0405_users.2.5.goss.yml
- roles/maxscale/tests/0405_users.2.5.yml
- roles/maxscale/tests/0406_users.6.1.goss.yml
- roles/maxscale/tests/0406_users.6.1.yml
- roles/maxscale/tests/pre_tasks/maxscale_2.5.yml
- roles/maxscale/tests/pre_tasks/maxscale_6.1.yml
Skipping version 6.0 since it's labelled as `beta` https://mariadb.com/kb/en/mariadb-maxscale-6-mariadb-maxscale-60-release-notes-2021-06-30/
> [Maxscale] Add support for 2.5 & 6.1

- CHANGELOG.md
- roles/composer/tasks/install.yml
Composer display a blocking warning when running in sudo mode:
The prevent the "install > Check" step from ever finishing.
The add of the "-n" (no-interaction) option fixes the problem.
> [Composer ] No interaction on install check to prevent blocking root warning

- CHANGELOG.md
- plugins/lookup/apt_keys.py
- roles/apt/vars/main.yml
- tests/unit/plugins/lookup/test_apt_keys.py
Debian 9 (stretch) is no longer supported by MySQL and apt key expired on 2022-02-16.
This PR removes legacy MySQL key and trusts repository on stretch.
On existing servers you need to remove previous apt list (`rm /var/list/repo.mysql.com_apt_debian_dists_stretch_* `)
> [Apt] Trust MySQL repository on stretch

- CHANGELOG.md
- plugins/modules/php_extension.py
;TLDR `check_rc=True` arg in ansible module.run_command does *NOT* mean "dude, check the return code, and give it back to me" but "dude, check the return code by yourself and break my module if its != 0"
> [Php] Fix extension handling when extension is already disabled

- molecule/mysql.mariadb.10.3/converge.yml
- molecule/mysql.mariadb.10.3/prepare.yml
- molecule/mysql.mariadb.10.4/converge.yml
- molecule/mysql.mariadb.10.4/prepare.yml
- molecule/mysql.mariadb.10.5/converge.yml
- molecule/mysql.mariadb.10.5/prepare.yml
- molecule/mysql.mariadb.10.6/converge.yml
- molecule/mysql.mariadb.10.6/prepare.yml
Now that debian stretch packages have been removed from mariadb repositories
> [MySQL] Remove mariadb debian stretch tests

- roles/docker/tasks/update.yml
For obscure reasons, docker role has kept the old-fashioned way of exclude linting rules using `skip_ansible_lint` tag
> [Docker] Fix linting

- CHANGELOG.md
- molecule/apt/goss/repositories.default.yml.j2
- roles/apt/vars/main.yml
Grafana have changed their apt repository around version `9.2` release date, from `https://packages.grafana.com/oss/deb` to `https://apt.grafana.com`. Key url also changed from `https://packages.grafana.com/gpg.key` to `https://apt.grafana.com/gpg.key`.
Look at:
- version `9.1` installation documentation: https://grafana.com/docs/grafana/v9.1/setup-grafana/installation/debian/#install-from-apt-repository
- version `9.2` installation documentation: https://grafana.com/docs/grafana/v9.2/setup-grafana/installation/debian/#install-from-apt-repository
I've double-checked, packages and key are strictly the same between both repos, only url changed.
> [Apt] Update grafana repository

- CHANGELOG.md
- molecule/telegraf/converge.yml
- roles/telegraf/templates/config/telegraf/base/telegraf.conf.j2
Based on last telegraf package version https://github.com/influxdata/telegraf/releases/tag/v1.25.0
Also fix molecule tests, where an output AND an input are now required in the config file.
> [Telegraf] Update base config template

- molecule/nodejs.18/goss/default.yml.j2
NodeJS 16 now comes with npm version 9
> [NodeJS] Fix v16 npm version test

- .github/workflows/collection-release.yaml
We split into 3 jobs (`building collection`, `publishing on ansible-galaxy` and `publishing on github`) and update versions of actions/replace deprecated actions
Needed for several reasons:
- Ansible-galaxy is a mess right now and upload could easily fail. We need to separate the upload to galaxy and the upload to github, so if one fails the other can succeed. Then it's at least possible to install manually the collection by downloading it on Github. The 2 process of publishing can occured simultaneously.
- Some deprecation coming from old versions of `action/core`, which were use in several third-party actions in our workflow. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [CI] Update release process

- requirements.yml
After trying alternative strategies (such as git or github releases), using direct `.tar.gz` downloading from ansible galaxy servers offers the opportunity to bypass (unreliable) ansible galaxy api, at the cost of hard setting collection versions in the url.
🗒️ this only concerns tests/linting requirements ! Collection requirements themselves are defined in `galaxy.yml`file.
> Update requirements strategy

- meta/runtime.yml
According to `meta-runtime[invalid-version]` lint rule (see: https://ansible-lint.readthedocs.io/rules/meta-runtime/) `2.14` is no more a valid version, we must set `2.14.0`
> Fix ansible version requirement

- molecule/grafana/goss/default.yml.j2
`grafana-server` bin has been merged into main `grafana`bin (with `server` arg)
> [Grafana] Fix process goss test

- CHANGELOG.md
- molecule/network/converge.yml
- molecule/network/goss/interfaces_configs.yml.j2
- molecule/network/goss/netplan_configs.yml.j2
- roles/network/README.md
- roles/network/defaults/main.yml
- roles/network/handlers/main.yml
- roles/network/meta/main.yml
- roles/network/tasks/main.yml
- roles/network/tasks/netplan_configs.yml
- roles/network/templates/netplan_configs/_default.j2
Debian Bookworm network is managed by Netplan + systemd-networkd. 
This PR add support netplan configuration files.
> [Network] Add Netplan configs support

- roles/bind/README.md
I think there are syntax errors in the examples for bind zone content. When I try to apply such examples I get this in the syslog:
```
Nov 23 14:50:07 ubuntu named[9780]: dns_rdata_fromtext: /var/cache/bind/db.bar.local:9: extra input text
```
> fix: README bind zone examples

- CHANGELOG.md
- molecule/maxscale.23.02/converge.yml
- molecule/maxscale.23.02/prepare.yml
- molecule/maxscale.23.08/converge.yml
- molecule/maxscale.23.08/prepare.yml
- molecule/php.5.6/converge.yml
- molecule/php.5.6/prepare.yml
- molecule/php.7.0/converge.yml
- molecule/php.7.0/prepare.yml
- molecule/php.7.1/converge.yml
- molecule/php.7.1/prepare.yml
- molecule/php.7.2/converge.yml
- molecule/php.7.2/prepare.yml
- molecule/php.7.3/converge.yml
- molecule/php.7.3/prepare.yml
- molecule/php.7.4/converge.yml
- molecule/php.7.4/prepare.yml
- molecule/php.8.0/converge.yml
- molecule/php.8.0/prepare.yml
- molecule/php.8.1/converge.yml
- molecule/php.8.1/prepare.yml
- molecule/php.8.2/converge.yml
- molecule/php.8.2/prepare.yml
- molecule/php.8.3/converge.yml
- molecule/php.8.3/prepare.yml
- molecule/postgresql.9.4/converge.yml
- roles/apt/vars/main.yaml
- Fix buster backports/backports_sloppy debian repository uris
- Remove MaxScale 23.02/23.08 buster tests
- Remove all php versions buster tests
- Allow both ipv4/ipv6 local postgresql connections
> [All] Mainly buster related fixes

- CHANGELOG.md
- molecule/fail2ban/converge.yml
- molecule/fail2ban/goss/default.yaml.j2
- roles/fail2ban/tasks/install.yaml
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770171
> [Fail2ban] Fix Bookworm sshd jail by installing python3-systemd

- CHANGELOG.md
- roles/mysql/tasks/users.yaml
Allow to provision MySQL/MariaDB users with TLS requirements.
> [MySQL] Supports `tls_requires` directive on `manala_mysql_users`
