manala/ansible-roles

manala.telegraf/CHANGELOG.md
manala.telegraf/templates/config/default.j2
manala.telegraf/tests/0200_config.yml
manala.telegraf/tests/0300_configs.yml

Fix broken tests + follow upstream package configuration.

Telegraf : Upstream config 1.3.0-1

---

manala.php/tasks/requirements.yml
manala.php/vars/main.yml

Allow multiple distribs for a given version of linux distrib

---

manala.alternatives/CHANGELOG.md
manala.alternatives/tasks/main.yml
manala.alternatives/tests/0100_selections.goss.yml
manala.alternatives/tests/0100_selections.yml
manala.apt/CHANGELOG.md
manala.apt/tasks/main.yml
manala.apt/tasks/repositories.yml
manala.deploy/CHANGELOG.md
manala.deploy/tasks/main.yml
manala.docker/CHANGELOG.md
manala.docker/tasks/main.yml
manala.grafana/CHANGELOG.md
manala.grafana/meta/main.yml
manala.grafana/tasks/dashboards.yml
manala.npm/CHANGELOG.md
manala.npm/tasks/main.yml
manala.php/CHANGELOG.md
manala.php/handlers/main.yml
manala.php/tasks/extensions.yml
manala.php/tasks/main.yml
manala.php/tasks/services.yml

Ansible 2.3 deprecations & warnings

---

manala.apt/CHANGELOG.md
manala.apt/README.md
manala.apt/vars/main.yml
manala.nodejs/CHANGELOG.md
manala.nodejs/tests/0106_install.8.goss.yml
manala.nodejs/tests/0106_install.8.yml
manala.nodejs/tests/pre_tasks/nodesource_8.yml
manala.skeleton/CHANGELOG.md
manala.skeleton/defaults/main.yml
manala.skeleton/vars/main.yml

Nodejs 8 support

---

manala.skeleton/CHANGELOG.md
manala.skeleton/vars/main.yml

[Skeleton] Add exa package from manala by default

---

manala.apt/CHANGELOG.md
manala.apt/README.md
manala.apt/vars/main.yml

[Apt] Backports sloppy support

---

manala.ohmyzsh/CHANGELOG.md
manala.ohmyzsh/templates/themes/default.demo.j2
manala.ohmyzsh/templates/themes/default.dev.j2
manala.ohmyzsh/templates/themes/default.prod.j2
manala.ohmyzsh/templates/themes/default.staging.j2

Fixes an issue with the prompt causing troubles with the terminal buffer when a line is longer than terminal width.

[OhMyZsh] Fix prompt

---

manala.apt/CHANGELOG.md
manala.apt/README.md
manala.apt/templates/sources_list/debian/default.j2
manala.apt/templates/sources_list/debian/default_src.j2
manala.apt/templates/sources_list/debian/security_updates.j2
manala.apt/templates/sources_list/debian/security_updates_ovh.j2
manala.apt/tests/0200_sources_list.goss.yml
manala.apt/tests/0500_repositories.goss.yml
manala.apt/tests/0500_repositories.yml
manala.apt/vars/main.yml
manala.cloud-init/tests/pre_tasks/backports.yml
manala.docker/tests/pre_tasks/backports.yml
manala.elasticsearch/tests/pre_tasks/backports.yml
manala.git/tests/pre_tasks/backports.yml
manala.haproxy/tests/pre_tasks/backports.yml
manala.java/tests/pre_tasks/backports.yml
manala.mongo-express/tests/pre_tasks/backports.yml
manala.rtail/tests/pre_tasks/backports.yml
manala.supervisor/tests/pre_tasks/backports.yml

Fix debian sources

---

manala.ohmyzsh/CHANGELOG.md
manala.ohmyzsh/templates/users/default.dev.j2
manala.ohmyzsh/templates/users/default.j2
manala.ohmyzsh/templates/users/default.prod.j2
manala.ohmyzsh/templates/users/php.dev.j2

See: https://github.com/robbyrussell/oh-my-zsh/pull/5603

[Oh My Zsh] Fix default user template ssh key path

---

manala.locales/CHANGELOG.md
manala.locales/tasks/main.yml

As seen on other roles, this is a more standard way to handle conditional cheks

[Locales] Fix weak conditional check

---

manala.apt/CHANGELOG.md
manala.apt/vars/main.yml

[Apt] Updates

---

manala.postgresql/CHANGELOG.md
manala.postgresql/README.md
manala.postgresql/handlers/main.yml
manala.postgresql/tasks/config.yml
manala.postgresql/tasks/services.yml

[PostgreSQL] Fix roles creation failure

---

manala.timezone/CHANGELOG.md
manala.timezone/defaults/main.yml
manala.timezone/tasks/default.yml
manala.timezone/templates/timezone/timezone.j2

[Timezone] Support /etc/localtime as link

---

manala.shorewall/CHANGELOG.md
manala.shorewall/tasks/config.yml

[Shorewall] Service restart on config changes

---

manala.deploy/CHANGELOG.md
manala.deploy/tasks/tasks/include_role.yml

[Deploy] Handle role inclusion

---

manala.elasticsearch/README.md
manala.elasticsearch/tasks/install.yml
manala.redis/tasks/install.yml

Using ansible block when possible

[All] Cleanup versions handling

---

manala.files/CHANGELOG.md
manala.files/README.md
manala.files/tasks/attributes/url.yml
manala.files/tests/0117_attributes.url.goss.yml
manala.files/tests/0117_attributes.url.yml

Example:
```
manala_files_attributes:
- path: /tmp/alt-galaxy.tar.xz
url:  https://github.com/gantsign/alt-galaxy/releases/download/1.4.0/alt-galaxy_linux_amd64.tar.xz
unarchive: true
creates:   /tmp/alt-galaxy
```

[Files] Handle url unarchiving

---

manala.network/CHANGELOG.md
manala.network/templates/interfaces/_macros.j2

This is a - de facto - standard

[Network] Tabulation based indentation for interfaces

---

manala.skeleton/CHANGELOG.md
manala.skeleton/defaults/main.yml
manala.skeleton/meta/main.yml
manala.skeleton/vars/main.yml

Delivered by forceps, and pain in the ass to maintain.

[Skeleton] Drop docker support

---

manala.skeleton/CHANGELOG.md
manala.skeleton/defaults/main.yml
manala.skeleton/vars/main.yml

...by using replace filters instead of fixed versions arrays

[Skeleton] Simplify "apt_preferences" mapping

---

manala.deploy/CHANGELOG.md
manala.deploy/README.md
manala.deploy/defaults/main.yml
manala.deploy/tasks/strategy/include.yml
manala.deploy/tests/0201_strategy.include.goss.yml
manala.deploy/tests/0201_strategy.include.yml
manala.deploy/tests/fixtures/strategy/include.yml

Allow custom strategy to pull code.

[Deploy] Add include strategy

---

manala.apt/CHANGELOG.md
manala.apt/vars/main.yml
manala.elasticsearch/CHANGELOG.md
manala.elasticsearch/defaults/main.yml
manala.elasticsearch/templates/config/7/_base.j2
manala.elasticsearch/templates/config/7/default.j2
manala.elasticsearch/tests/0206_install.7.goss.yml
manala.elasticsearch/tests/0206_install.7.yml
manala.elasticsearch/tests/0306_config.7.goss.yml
manala.elasticsearch/tests/0306_config.7.yml
manala.elasticsearch/tests/0506_plugins.7.goss.yml
manala.elasticsearch/tests/0506_plugins.7.yml
manala.elasticsearch/tests/pre_tasks/elasticsearch_7.yml
manala.skeleton/CHANGELOG.md
manala.skeleton/defaults/main.yml
manala.skeleton/vars/main.yml

Added elasticsearch version 7 support based on https://github.com/manala/ansible-roles/pull/178

[Elasticsearch] add version 7 support

---

manala.supervisor/CHANGELOG.md
manala.supervisor/templates/configs/app_program.dev.j2
manala.supervisor/templates/configs/app_program.prod.j2
manala.supervisor/templates/configs/app_program.test.j2
manala.supervisor/templates/configs/inet_http_server.dev.j2
manala.supervisor/templates/configs/inet_http_server.prod.j2
manala.supervisor/templates/configs/program.dev.j2
manala.supervisor/templates/configs/program.prod.j2
manala.supervisor/templates/configs/program.test.j2

[Supervisor] Update configs templates based on version 3.3.5

---

manala.apt/CHANGELOG.md
manala.apt/vars/main.yml

First step for MySQL 8 support.

[Apt] Add mysql 8 repository pattern

---

manala.composer/CHANGELOG.md
manala.composer/README.md
manala.composer/defaults/main.yml
manala.composer/tasks/install.yml
manala.composer/tests/0110_install_version.goss.yml
manala.composer/tests/0110_install_version.yml

Add `manala_composer_version` variable to define the composer version to install.

[Composer] Allow to specify version to install

---

roles/accounts/CHANGELOG.md
roles/accounts/tasks/groups.yml
roles/accounts/tasks/users.yml

Conform to other roles, and not need jinja >= 2.8

[Accounts] Fix user & group state handling

---

roles/proftpd/CHANGELOG.md
roles/proftpd/defaults/main.yml
roles/proftpd/tasks/users.yml
roles/proftpd/templates/users/default.j2
roles/proftpd/tests/0300_users.yml

Add automatic home directories creation for virtual users

[PROFTPD] Add directories creation for virtuals users

---

roles/proftpd/CHANGELOG.md
roles/proftpd/README.md
roles/proftpd/defaults/main.yml
roles/proftpd/tasks/users.yml
roles/proftpd/tests/0300_users.goss.yml
roles/proftpd/tests/0300_users.yml

Close https://github.com/manala/ansible-roles/issues/417

[Proftpd] Fix default home directory mode

---

roles/php/CHANGELOG.md
roles/php/tasks/main.yml

[Php] Fix missing configs tags

---

CHANGELOG.md
roles/ohmyzsh/CHANGELOG.md
roles/ohmyzsh/templates/users/default.dev.j2
roles/ohmyzsh/templates/users/default.j2
roles/ohmyzsh/templates/users/default.prod.j2
roles/ohmyzsh/templates/users/php.dev.j2

See: https://github.com/ohmyzsh/ohmyzsh/pull/8960

[Oh My Zsh] Update users templates

---

CHANGELOG.md
roles/files/CHANGELOG.md
roles/files/action_plugins/manala_files_attributes.py

See: https://github.com/manala/ansible-roles/pull/488

[Files] Fix task_vars issues #2

---

CHANGELOG.md
roles/php/CHANGELOG.md
roles/php/templates/configs/xdebug.dev.j2
roles/php/templates/configs/xdebug.test.j2

See: https://xdebug.org/docs/upgrade_guide
Fix https://github.com/manala/ansible-roles/issues/535

[Php] Fix XDebug 3 configuration templates

---

roles/composer/README.md

[Composer] fix typo

---

CHANGELOG.md
roles/apt/CHANGELOG.md
roles/apt/README.md
roles/apt/vars/main.yml
roles/nodejs/tests/0111_install.16.goss.yml
roles/nodejs/tests/0111_install.16.yml
roles/nodejs/tests/pre_tasks/nodesource_16.yml

https://nodejs.org/en/blog/release/v16.0.0/

Added support for Node 16

---

prepare_collection.py
runtime.yml

Mandatory now -> https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_structure.html#meta-directory

[Collection] Add meta/runtime.yml

---

CHANGELOG.md
roles/apt/vars/main.yml

[Apt] Fix kopia key id

---

README.md

A little bafouille on how to test this shit

[Doc] Readme development

---

CHANGELOG.md
roles/apt/vars/main.yml

Fix https://bugs.mysql.com/bug.php?id=106188

[Apt] Add new Mysql key id and rename the old one `mysql_legacy`

---

CHANGELOG.md
molecule/mysql.5.7/converge.yml
molecule/mysql.5.7/goss/client.yml.j2
molecule/mysql.8.0/converge.yml
molecule/mysql.8.0/goss/client.yml.j2
molecule/mysql.mariadb.10.6/converge.yml
molecule/mysql.mariadb.10.6/goss/client.yml.j2
molecule/ssh/converge.yml
roles/mysql/README.md
roles/mysql/defaults/main.yml
roles/mysql/tasks/data_dir.yml
roles/mysql/tasks/databases.yml
roles/mysql/tasks/replications.yml
roles/mysql/tasks/services.yml
roles/mysql/tasks/users.yml
roles/ssh/README.md

Handle server/client provisionning, on the model of `ssh`role

[MySQL] Server/Client

---

CHANGELOG.md
roles/apt/vars/main.yml

See: https://symfony.com/download

[Apt] Add symfony repository

---

.github/workflows/molecule.mysql.yaml
CHANGELOG.md
molecule/mysql.galera.4.10.mysql_wsrep.8.0.26/converge.yml
molecule/mysql.galera.4.10.mysql_wsrep.8.0.26/goss/default.yml.j2
molecule/mysql.galera.4.10.mysql_wsrep.8.0.26/prepare.yml
roles/apt/vars/main.yml

Galera 4.10 is required to install Galera to Debian 11.

[Apt] Add Galera 4.10 and MySQL wsrep 8.0.26 repositories

---

CHANGELOG.md
roles/mysql/tasks/databases.yml
roles/mysql/tasks/users.yml

Allows to manage users and databases on remote server or via linux socket.

[MySQL] Add login parameters for users and databases tasks

---

CHANGELOG.md
molecule/mysql.mariadb.10.6/converge.yml
roles/mysql/defaults/main.yml
roles/mysql/tasks/install.yml

Allows to use `pymysql` python library to run users and databases tasks.

[MySQL] Python installed package is configurable

---

roles/apt/vars/main.yml

See: https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt

[Apt] GitHub cli repository

---

CHANGELOG.md
roles/apt/vars/main.yml

See: https://github.com/cli/cli/commit/23933fd527b9f0e96faab24ac8ede8f8d9233448

[Apt] Fix github cli key

---

molecule/grafana/converge.yml
molecule/grafana/goss/default.yml.j2
roles/grafana/tasks/dashboards.yml
roles/grafana/tasks/datasources.yml

Tests have also been adjusted to prevent failure in case of a slow starting services.

[Grafana] Force json uri calls

---

roles/accounts/tasks/users.yml
roles/ansible_galaxy/tasks/roles.yml
roles/apt/tasks/holds.yml
roles/apt/tasks/update.yml
roles/aptly/tasks/repositories.yml
roles/composer/tasks/install.yml
roles/deploy/tasks/copied.yml
roles/deploy/tasks/strategy/git.yml
roles/deploy/tasks/tasks/command.yml
roles/deploy/tasks/tasks/install_composer.yml
roles/deploy/tasks/tasks/make.yml
roles/docker/tasks/update.yml
roles/elasticsearch/tasks/install.yml
roles/gitlab/handlers/main.yml
roles/grafana/tasks/install.yml
roles/influxdb/tasks/databases.yml
roles/influxdb/tasks/privileges.yml
roles/influxdb/tasks/users.yml
roles/mysql/tasks/data.yml
roles/mysql/tasks/data_dir.yml
roles/nginx/handlers/main.yml
roles/npm/tasks/requirements.yml
roles/ohmyzsh/tasks/requirements.yml
roles/ohmyzsh/tasks/users.yml
roles/pam_ssh_agent_auth/tasks/requirements.yml
roles/php/handlers/main.yml
roles/php/tasks/install.yml
roles/redis/tasks/install.yml
roles/ssh/tasks/install.yml
roles/timezone/tasks/default.yml

Before:
```yaml
- name: Foo  # comment
ansible.builtin.shell: >
foo
bar
```
After:
```yaml
- name: Foo
ansible.builtin.shell:  # comment
cmd: >
foo
bar
```

[All] Use long form command/shell modules

---

roles/ansible_galaxy/tasks/roles.yml
roles/apt/tasks/update.yml
roles/aptly/tasks/repositories.yml
roles/deploy/tasks/copied.yml
roles/deploy/tasks/tasks/install_composer.yml
roles/deploy/tasks/writable/dirs.yml
roles/mysql/tasks/data.yml
roles/mysql/tasks/data_dir.yml
roles/timezone/tasks/default.yml

See: https://ansible-lint.readthedocs.io/rules/no-changed-when/

No changed when

---

roles/bind/README.md

Replace https://github.com/manala/ansible-roles/pull/686

Bind: README.md: Fixed bad documentation for Zones - Dynamic
